### PR TITLE
Build

### PR DESCRIPTION
**Pull request by drernie**

### CODE REVIEW

**Comment by drernie** [comment]
Assuming this is abandoned. Will maintain my own fork...

**Comment by dacort** [comment]
Not necessarily abandoned, just haven't had to use it myself. But this looks like a great PR to modernize the dependencies for sure.

**Comment by drernie** [comment]
Ah! This includes #13.  If you are still open to maintaining this, I will PR my changes after I merge them into my own fork.

**Comment by dacort** [comment]
That'd be awesome and much appreciated!

**Pull request closed without merging**
